### ISSUE TITLE
Incorrect Authentication.

### ISSUE THREAD

**Issue by fabiocanella** [irontec/zsugar#14]
I have zimbra 8.5 and sugarcrm Version 6.5.18 (Build 1110) I  installed the zimbra but I have this error:

Incorrect Authentication.
zsugar 1.4.14
<% /\* \* ------ Zimbra - Sugar

The zimlet is compatible with my software version ?

**Comment by rholighaus** [comment]
I have upgraded to ZCS 8.7.0 and now getting the message

```
Incorrect Authentication.
zsugar 1.4.14
```

again :-(

Have you tested zsugar on Zimbra 8.7.0?

Please let me know if I can provide any help!

Ralf.

**Comment by rholighaus** [comment]
Just installed 1.4.15 and it's working again. Sorry, should have tried that before.
R.

**Comment by Kaian** [comment]
No problem! We're using it with 8.0.7 so it's nice to know it works in newer versions!
