### ISSUE TITLE
Create from task: new case, opportunity or task  - feature request

### ISSUE THREAD

**Issue by rholighaus** [irontec/zsugar#15]
This would allow to replace existing (crap) Sugar E-Mail client.

Subject of e-mail would become subject of case/opportunity/task, body of e-mail would become body of the new sugar object. 

If contact exists for e-mail, maybe even link the new object to that contact?

**Comment by Kaian** [comment]
Hi @rholighaus !

  It sounds like a nice feature, but right now we lack the resources for developing new features, so we prefer to focus on bugfixing and compatibility issues. Anyway we'll take this request into account if we have time in the future.

  If you feel the need for this feature to be implemented right now, feel free to contact comercial@irontec.com and we'll try to squeeze its development in our schedule :)

Thanks for your request!
