### ISSUE TITLE
Send to SugarCRM no displayed leads

### ISSUE THREAD

**Issue by sasha2002** [irontec/zsugar#16]
After i press "Send to SugarCRM" button, dialog is open and i got errors in console(firebug) :
http://joxi.ru/V2V3pnc0E4lGAv 
If i press create lead, lead is created but can't archive because of error.

I use SuiteCRM and Zimbra 8.6.0

**Comment by Kaian** [comment]
Hi @sasha2002 

Thanks for reporting!. 

I'll try to reproduce this issue as soon I can. I have little spare time right now, but I will try to maintain this zimlet again :)
