### ISSUE TITLE
Incorrect Authentication. Zsugar 1.4.15 on Zimbra 8.8.5 GA 

### ISSUE THREAD

**Issue by amernet** [irontec/zsugar#18]
Hello,

Since we upgraded the zimbra to 8.8.5, my zSugar stopped working. I checked the JSP is still enabled.

Zsugar 1.4.15 on Zimbra 8.8.5_GA_1894 (build 20171026035615)

Please advise how to fix it. 

Thanks!

**Comment by Kaian** [comment]
Hi @amernet 

zsugar has not been tested in zimbra > 8.7 but let's try to find out what's failing.

This zimlet requests are sent using a JSP, so the best way to debug is opening your browser developers tools and reload. Look for redirect.jsp request and check the response (you can paste it here)

I've attached an image of latest firefox developer tools (pressing F12 in zimbra webmail).

![redirectjsp](https://user-images.githubusercontent.com/800069/35216689-bae28bb2-ff68-11e7-9ab6-e4b6ff104a86.png)

Thanks for reporting!

**Comment by amernet** [comment]
Hello Kaian,

Sorry for the late reply.
Please let me know if this is what you want to see.

------------------------------------- Loading package: ZimletApp
VM7473:1 POST https://zmail.amer.net/service/zimlet/com_irontec_zsugar/redirect.jsp 500 (Server Error)
(anonymous) @ VM7473:1
(anonymous) @ Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:34064
AjxRpcRequest.invoke @ Startup1_1_all.js.zgz?v=171026050723:1331
AjxRpc.invoke @ Startup1_1_all.js.zgz?v=171026050723:1422
ironsugar._doPOST @ Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:59210
ironsugar._callREST @ Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:59228
ironsugar.login @ Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:59247
com_irontec_zsugarH._login @ Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:59573
com_irontec_zsugarH.init @ Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:59501
ZmZimletContext._finished_loadIncludes @ VM7541:701
ZmZimletMgr._finished_loadIncludes @ VM7541:1393
AjxCallback.run @ (index):1481
e @ Startup1_1_all.js.zgz?v=171026050723:4055
(anonymous) @ (index):1514
Zimlets-nodev_all.js.zgz?language=en&country=US&cosId=e00428a1-0c00-11d9-836a-000d93afea2a:

**Comment by amernet** [comment]
![redirect_jsp](https://user-images.githubusercontent.com/7107961/37229486-f0f422de-2398-11e8-87b4-87acdd848464.png)

**Comment by amernet** [comment]
![screenshot_1](https://user-images.githubusercontent.com/7107961/37229956-adb7aebc-239a-11e8-8e4a-1f37b18dbb9b.png)

**Comment by Kaian** [comment]
Sorry for the late response, you closed the issue so it disappeared from my view :sweat_smile: 

The 500 error of that response does not provide too much information. We would require the zimbra logs when the request is done to have more information.

Also, like documentation mentions, be sure you have restarted your mailbox and enabled JSP (See https://github.com/irontec/zsugar/issues/2#issuecomment-55773282) .

Sorry I can not provide better support, but sadly we have stopped using SugarCRM so this plugin has not improved since a year..

Regards!
