### ISSUE TITLE
Error when trying to deploy zSugar Zimbra 8.8.8

### ISSUE THREAD

**Issue by mmorton235** [irontec/zsugar#19]
When i try to deploy zSugar i get the error 

Critical | Server error encounteredMessage: system failure: error deploying Zimlet Error code: service.FAILURE Method: [unknown] Details:soap:Receiver
-- | --

**Comment by Kaian** [comment]
Hi @mmorton235 

What Zimbra version are you using?


Regards

**Comment by mmorton235** [comment]
i'm using 8.8.8 i know you are no longer looking into zSugar but do you have any ideas on what could be done i was getting the Incorrect Authentication error when i had it deployed tried redeploying it and got the error above also under the console in f12 mode i'm getting a 500 error when the other error occurs

**Comment by Kaian** [comment]
I didnt experienced this error before. Are you deploying from command line or interface? Maybe there are more detailed info in zimbra logs (i think there is a log directory somewhere).

Not sure if the zimlets format have changed or expects different information in the mail .xml.
We don't use SugarCRM anymore, so the development of this zimlet has stopped.

Apart from the classic "restart your mailbox after deploying" and "[enable JSP for zimlets](https://github.com/irontec/zsugar/issues/2#issuecomment-55773282)", sadly I can give you further advice. And all of those are after deploying :-/

**Comment by mmorton235** [comment]
i'm deploying from the interface and it's popping up i haven't found that error anywhere else online, i'll try to find the logs and sort through them for any helpful information

**Comment by mmorton235** [comment]
thank you for your time and help

**Comment by Kaian** [comment]
Most probably too late after so many years but at least for the record...

It seems bTactic for has a release that works in zimbra 8.8.15

https://github.com/btactic/zsugar/releases

Regards
