### ISSUE TITLE
Create Contact did not populate Account field

### ISSUE THREAD

**Issue by gjsjohnmurray** [irontec/zsugar#4]
Using zsugar 1.4.12 from Zimbra 8.0.7 to SugarCRM CE 6.5.14, I used the "Create Contact" option from the "More options" button. The dialog appeared and firstname, lastname and email address were in the first 3 fields. The "Assign created contact to my user" box was checked.

I typed an existing account name into the "Contact account" field, then clicked OK.

Over in SugarCRM the new contact existed but their Account field was empty.

**Comment by Kaian** [comment]
Hi !

Sorry for all this time of inactivity. I have been working in other projects and totally forgot zsugar all this time.

I was unable to reproduce this problem in zsugar 1.4.15 
Account field is handled like text both in zsugar and sugarcrm, and it seems to work with anything I enter in the input.

Feel fee to reopen if problem can be reproduced.

Thanks!

**Comment by gjsjohnmurray** [comment]
This was specifically about "Create Contact" rather than "Create Lead". I think "Create Contact" appeared in 1.4.12 along with "Create Opportunity" and "Create Case" but you then withdrew that release.

**Comment by Kaian** [comment]
Ohh, sorry. You're right.

Yes, that changes were too unstable to release them.
Back then, we had too many other tasks and somehow this zimlet become unmantained.

Most probably we won't add any more functionality to this zimlet: It's code is a mess.
I will prefer to start a new zimlet from scratch or continue working on zsugarplus.

Anyway, thanks a lot for dropping by to clarify the issue :)
